### ISSUE TITLE
Will you support Debug Actions?

### ISSUE THREAD

**Issue by imdatcandan** [Gridstone/DebugDrawer#16]
A mechanism for adding debug actions to the dev drawer. An example of a debug action is "login" Typing out a lot of text,such as email password etc

**Comment by chris-horner** [comment]
Not sure what kind of default mechanism you're after. If you want to add an action to the drawer you can create your own module quite easily.

```kotlin
class MyActionModule : DebugDrawerModule {

  override fun onCreateView(parent: ViewGroup): View {
    val button = Button(parent.context)
    button.setText(R.string.do_a_thing)
    button.setOnClickListener {
      // Do what you need to do.
    }

    return button
  }
}
```

Is there something in particular you had in mind?

Sorry for the late response, I hadn't configured notifications correctly!

**Comment by chris-horner** [comment]
Closing this for now due to a lack of activity.
