### ISSUE TITLE
Update Leakcanary module to support version 2.0

### ISSUE THREAD

**Issue by chris-horner** [Gridstone/DebugDrawer#19]
I'm of two minds about doing this now or waiting until PY takes it out of alpha. On one hand it'd be nice to wait until the API stabilises. On the other hand there're so many improvements in 2.0 that'd be great to take advantage of even while it's in alpha. (DebugDrawer itself isn't even 1.0 yet 😉).

One solution might be to make a new module for 2.0 and keep them separate? 🤷‍♂

**Comment by jsprincep** [comment]
Up to you, but I'd be hesitant, just based on the issues we've encountered using previous 'latest' versions of LeakCanary, let alone alpha or beta builds. That said, if you have the time to make a separate module, go for it, there's no real risk in that. 😀
