### ISSUE TITLE
When will you plan to release LeakCanary2 module that supports 2.0-beta-3?

### ISSUE THREAD

**Issue by imdatcandan** [Gridstone/DebugDrawer#37]

**Comment by chris-horner** [comment]
You can get at `0.9.7-SNAPSHOT` if you're willing to add
```groovy
maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
```
to your project's repositories. I was planning on waiting until Google released a non-alpha version of DrawerLayout `1.1.0`, but it's looking like that might not happen any time soon. I'll consider pushing out a new stable release some time this week 🙂

**Comment by imdatcandan** [comment]
@chris-horner I would be gladly happy when you release the new version soon. Thanks for this great library <3

**Comment by chris-horner** [comment]
Once #38 is addressed I'll push a new release 🙂
