### ISSUE TITLE
Close Drawerlayout nicely

### ISSUE THREAD

**Issue by kittinunf** [Gridstone/DebugDrawer#38]
Hey, thanks for this awesome library!

Btw, we ran into the situation where we want to add a feature flag on the `Drawerlayout` and navigate the app to somewhere. The problem we ran into is how to programmatically close the `Drawerlayout` after the transition is completed.

Currently, workaround is kinda hacky like the following;

``` kotlin
//inside the custom class that implements the DebugDrawerModule

activity.findViewById<DrawerLayout>(R.id.debugDrawerId).closeDrawers()
```

Do you have a better way to achieve this?

**Comment by chris-horner** [comment]
Glad you find it useful!

That's a really great use case we didn't consider. I wonder if we should add a new function? It'd wouldn't be too hard to expose something like:
```kotlin
DebugDrawer.from(activity).close()
```
Would an `open()` function be useful too?

**Comment by kittinunf** [comment]
Yes! That could work, also if you can somehow make the subclass of `DebugDrawerModule` being able to grab a hold of `DrawerLayout` reference, that might work as well.

But doing that you might have to turn `DebugDrawerModule` to an abstract class though.

**Comment by chris-horner** [comment]
Or perhaps change the signatures of `onAttach()` and `onDetach()` to get a `DrawerLayout`?

**Comment by kittinunf** [comment]
Something like `fun onAttach(drawerlayout: DrawerLayout)`?

yeah, that could work! But to use it might be a little awkward because you need to somehow hold the reference manually.

I am not sure I am mistaken but something like this?
```kotlin
class FooModule : DebugDrawerModule {
  
  var dl: DrawerLayout?

  fun onCreate() {

  }

  fun onAttach(drawerLayout: DrawerLayout) {
    dl = drawerLayout
  }
}
```

**Comment by chris-horner** [comment]
Yeah, thinking about it a bit more, `onAttach()` isn't a great place to put this. Maybe `onCreateView()` is more appropriate? It would allow for something like:
```kotlin
object FooModule : DebugDrawerModule {

  override fun onCreateView(parent: ViewGroup, drawer: DrawerLayout): View {
    val view: View = parent.inflate(R.layout.foo)
    val button: Button = view.findViewById(R.id.fooButton)
    button.setOnClickListener { drawer.close() }
    return view
  }
}
```
Still not great though for your scenario of closing the drawer after a transition. Moreover, it does ruin the neat signature of `onCreateView()`.

Perhaps the
```kotlin
DebugDrawer.from(activity).close()
```
is the best solution after all?

**Comment by kittinunf** [comment]
I personally prefer the `onCreateView` variant even though it is not great for my scenario, it looks slightly cleaner than just grabbing `DebugDrawer` out of the blue which may or may not be accessible at that time (`DebugDrawer.from(activity)`) look like it is singleton-ish ...

Yes, I don't really like the `onAttach`, either.

All in all, I am fine with both options 🙆‍♂ 👍
