### ISSUE TITLE
0.9.7 http logger problem

### ISSUE THREAD

**Issue by imdatcandan** [Gridstone/DebugDrawer#44]
Hey thanks for release but I got this error. Is there smth wrong on release?
ERROR: Failed to resolve: au.com.gridstone.debugdrawer:debugdrawer-okhttp-logger:0.9.7

**Comment by chris-horner** [comment]
Yep, see #43

**Comment by chris-horner** [comment]
Looks like Central was just taking its sweet time. We're good now 🎉
