### ISSUE TITLE
Add support to add our own views

### ISSUE THREAD

**Issue by ShivamDev31** [Gridstone/DebugDrawer#47]
Can we add support for adding our own views?
I know I can add a new module to add new feature.

But lets say I just want to add a Crash button in the drawer to crash my application. Adding a module is too much for work for that.

Maybe adding kotlin dsl like this: https://github.com/antonKozyriatskyi/DevDrawer will be helpful.

**Comment by chris-horner** [comment]
The DSL idea is certainly interesting and something I've been considering. The problem is achieving a balance of adding simple views and actions, and adding complex modules that need lifecycle callbacks.

For now, it's not horrendous to write:
```kotlin
class MyActionModule : DebugDrawerModule {

  override fun onCreateView(parent: ViewGroup): View {
    val button = Button(parent.context)
    button.setText(R.string.do_a_thing)
    button.setOnClickListener {
      // Do what you need to do.
    }

    return button
  }
}
```
However I get your point.

**Comment by ShivamDev31** [comment]
Thanks. As of now will add modules itself.
