### ISSUE TITLE
Feature enhancement request: Set defaults for logger and Leak Canary modules

### ISSUE THREAD

**Issue by thereallukesimpson** [Gridstone/DebugDrawer#52]
Hey Chris. In the `HttpLogger` is it possible to expose the `setLevel` method so that we can set the default to `BODY`? I find new starters get confused why they can't see network logs so would like to have it on by default with the option to turn it off or change log level.

Similarly, I'd like to be able to have Leak Canary switched off by default.

Please let me know if I'm missing something or if this could be an enhancement. Thanks!

**Comment by chris-horner** [comment]
Hey Luke!

No, there's no way to change the default currently but I think that would make a great addition. Maybe as a constructor param on `OkHttpLoggerModule`.

Similar approach could be adopted for LeakCanary. Though one could argue that should always be on by default 😉

**Comment by thereallukesimpson** [comment]
Haha I knew you'd say that about LeakCanary! 😆 

It's cool I'm much more concerned with the Logger module. Adding a constructor param sounds good; I'll put up a PR soon-ish. Thanks!

**Comment by thereallukesimpson** [comment]
Hey, do I need permission to push a branch to this repo? Getting: `remote: Permission to Gridstone/DebugDrawer.git denied to thereallukesimpson.`

I'm using a personal access token as per recent changes so not quite sure what's up!

**Comment by chris-horner** [comment]
Public repos like this work a little differently! You'll first need to fork it and make your branch there. Steps can [be found here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by chris-horner** [comment]
Closed in #70
